name: Build FFmpeg Shared Libraries for Windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup MSYS2
      # You may pin to the exact commit or the version.
      # uses: msys2/setup-msys2@cc11e9188b693c2b100158c3322424c4cc1dadea
      uses: msys2/setup-msys2@v2
      with:
        # Variant of the environment to set by default: MSYS, MINGW32, MINGW64, UCRT64, CLANG32, CLANG64 or CLANGARM64
        msystem: MINGW64
        # Default value for MSYS2_PATH_TYPE environment variable: strict, inherit or minimal
        path-type: minimal
        # Update MSYS2 installation through pacman
        update: true
        # After installation and/or update, install additional packages through pacman
        install: nasm
        # After installation and/or update, install additional packages through pacboy
        pacboy: none
        # Retrieve and extract base installation from upstream GitHub Releases
        release: true
        # Where to install MSYS2
        location: RUNNER_TEMP
        # What to do when run on an incompatible runner: fatal, warn
        platform-check-severity: fatal
        # If caching should be used
        cache: true
       
      

    - name: Build FFmpeg Shared Libraries
      run: |
        ./configure --toolchain=msvc --enable-shared --prefix=${GITHUB_WORKSPACE}/build
        make

    - name: Upload Built FFmpeg Shared Libraries as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: ffmpeg-shared-libraries
        path: ${{ github.workspace }}\build
