name: Build FFmpeg Shared Libraries for Windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Cygwin Action
      # You may pin to the exact commit or the version.
      # uses: cygwin/cygwin-install-action@006ad0b0946ca6d0a3ea2d4437677fa767392401
      uses: cygwin/cygwin-install-action@v4
      with:
        # Platform [x86, x86_64]
        platform: x86_64
        # Packages to install
        packages: |
          gcc-mingw-core 
          mingw-runtime
          mingw-zlib
        # Installation directory
        install-dir: C:\cygwin
        # Should the setup.ini file signature be checked?
        check-sig: true
        # Absolute paths of extra public key files (RFC4880 format), separated by whitespace
        pubkeys: none
        # Download site URLs separated by whitespace
        site: https://sourceware.mirror.garr.it/cygwin/
        # Should Cygwin's bin directory be added to the system PATH?
        add-to-path: true

    - name: Build FFmpeg Shared Libraries
      run: |
        echo ${GITHUB_WORKSPACE}
        ./configure --target-os=mingw32 --enable-shared --disable-static --extra-cflags=-mno-cygwin --extra-libs=-mno-cygwin --prefix=${GITHUB_WORKSPACE}\build
        make

    - name: Upload Built FFmpeg Shared Libraries as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: ffmpeg-shared-libraries
        path: ${{ github.workspace }}\build
